<?php

namespace Annuaire\AnnuaireBundle\Entity;

/**
 * CategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategorieRepository extends \Doctrine\ORM\EntityRepository
{
    public function findAllavecImg($nmb)
    {
        return $this->createQueryBuilder('c')
                    ->leftJoin('c.image', 'i')->addSelect('i')
                    ->orderBy('c.id', 'DESC')
                    ->setMaxResults($nmb)
                    ->getQuery()
                    ->getResult() ;
    }
    
    
    public function getCategories(){
        return $this->createQueryBuilder('ct')
                    ->orderBy('ct.nom', 'ASC')
                    ->getQuery()
                    ->getResult() ;
    }
}
