<?php

namespace Annuaire\AnnuaireBundle\Entity;

/**
 * CodepostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CodepostRepository extends \Doctrine\ORM\EntityRepository
{
}
