<?php

namespace Annuaire\AnnuaireBundle\Entity;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    public function getSliderImages(){
        return $this->createQueryBuilder('i')
                    ->where("i.type = 'slidehome'")
                    ->orderBy('i.position', 'ASC')
                    ->getQuery()
                    ->getResult() ;
    }
    public function getPrestSliderImages($id){
        return $this->createQueryBuilder('i')
                    ->where("i.type = 'slideprest'")
                    ->andWhere("i.user = :id")
                    ->setParameter('id', $id)
                    ->orderBy('i.position', 'ASC')
                    ->getQuery()
                    ->getResult() ;
    }
    public function getPrestGalImages($id){
        return $this->createQueryBuilder('i')
                    ->where("i.type = 'galprest'")
                    ->andWhere("i.user = :id")
                    ->setParameter('id', $id)
                    ->orderBy('i.position', 'ASC')
                    ->getQuery()
                    ->getResult() ;
    }
    
}
