<?php

namespace Annuaire\AnnuaireBundle\Entity;

/**
 * ImageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImageRepository extends \Doctrine\ORM\EntityRepository
{
    
    
    public function getSliderImages(){
        return $this->createQueryBuilder('i')
                    ->where("i.type = 'slidehome'")
                    ->orderBy('i.position', 'ASC')
                    ->getQuery()
                    ->getResult() ;
    }
}
