<?php

namespace Annuaire\AnnuaireBundle\Entity;

/**
 * LocaliteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LocaliteRepository extends \Doctrine\ORM\EntityRepository
{
    public function getLocalites(){
        return $this->createQueryBuilder('l')
                    ->orderBy('l.localite', 'ASC')
                    ->getQuery()
                    ->getResult() ;
    }
}
