<?php

namespace Annuaire\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;

/**
 * PrestataireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrestataireRepository extends EntityRepository
{
    public function getDerniers($nmb){
        return $this->createQueryBuilder('p')
                    ->leftJoin('p.codepost_id', 'cp')->addSelect('cp')
                    ->leftJoin('p.localite_id', 'l')->addSelect('l')
                    ->leftJoin('p.commune_id', 'c')->addSelect('c')
                    ->orderBy('p.dateInscr', 'DESC')
                    ->setMaxResults($nmb)
                    ->getQuery()
                    ->getResult() ;
    }
    
    public function getPrestataireProfil($id)
    {
        return $this->createQueryBuilder('p')
                    ->where('p.id = :id')
                    ->leftJoin('p.promos', 'pr')->addSelect('pr')
                    ->leftJoin('p.stages', 'st')->addSelect('st')
                    ->leftJoin('p.categories', 'cat')->addSelect('cat')
                    ->leftJoin('p.images', 'i')->where("i.type = 'logo'")->andWhere("i.user = :id")->addSelect('i')
                    ->setParameter('id', $id)
                    ->getQuery()
                    ->getResult() ;
    }
    
    public function findPrest($prest,$loc, $cat)
    {
        $qb = $this->createQueryBuilder('p');
        
        $qb = $qb->where($qb->expr()->like('p.nomprest', $qb->expr()->literal('%'.$prest.'%')))
                
                    ->andWhere('p.localite_id = :loc')
                    ->leftJoin('p.images', 'i', "WITH", "i.type = 'logo'")->addSelect('i') //->where("i.type = 'logo'")
                    ->leftJoin('p.categories', 'cat')->addSelect('cat')//->where("cat.id = :cat")
                    ->setParameter('loc', $loc)
                    //->setParameter('cat', $cat)
                    ->orderBy('p.nomprest')
                    ->getQuery()
                    ->getResult() ;
        
    }
}   
