<?php

namespace Annuaire\AnnuaireBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Query\Expr;
use Annuaire\AnnuaireBundle\Entity\User;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function getDeleteUser($id){
        /* pour pouvoir supprimer un user,
            il faut ajouter dans les entities-fils des annotations permettantes d'effacer l'id de prestataire supprimé,
            si non, doctrine n'executera cette commande.
                Donc, j'ai ajouté dans les entities comme Stage, promo, Image, Comment, Note, Favorite
                des annotations suivantes : nullable=true, onDelete="SET NULL"
                * @ORM\JoinColumn(name="prestataire", referencedColumnName="id", nullable=true, onDelete="SET NULL")
                  */
       
        $qb = $this->createQueryBuilder('u');
        $qb = $qb->delete('AnnuaireAnnuaireBundle:User','u');
        $qb = $qb->where('u.id = :id');
        $qb = $qb->setParameter('id', $id);
        

        $qb->getQuery()->execute();
    }
}
