annuaire_homepage:
    path:     /
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:index }
    
inscription_form:
    path:     /inscription
    defaults: { _controller: AnnuaireAnnuaireBundle:User:inscription }