annuaire_homepage:
    path:     /
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:index }

search:
    path:     /recherche
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:recherche }
    
prestataire_profil:
    path:     /prestataire-profil/{id}
    defaults: { _controller: AnnuaireAnnuaireBundle:User:profilPrest }
    
categorie_show:
    path:     /categorie/{id}
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:showCateg }
    
fos_user_profile_show:
    path: /profile
    defaults: { _controller: AnnuaireAnnuaireBundle:Profile:show  }
    
fos_user_profile_edit:
    path: /profile/edit
    defaults: { _controller: AnnuaireAnnuaireBundle:Profile:edit }  
    
user_delete:
    path: /user/delete/{id}
    defaults: { _controller: AnnuaireAnnuaireBundle:User:delete }
    

