annuaire_homepage:
    path:     /
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:index }
    
inscription_form:
    path:     /inscription
    defaults: { _controller: AnnuaireAnnuaireBundle:User:inscription }
    
prestataire_profil:
    path:     /prestataire-profil/{id}
    defaults: { _controller: AnnuaireAnnuaireBundle:User:showProfil }
    
categorie_show:
    path:     /categorie/{id}
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:showCateg }
    