annuaire_homepage:
    path:     /
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:index }

search:
    path:     /recherche
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:recherche }
    
prestataire_profil:
    path:     /prestataire-profil/{id}
    defaults: { _controller: AnnuaireAnnuaireBundle:User:profilPrest }
    
categorie_show:
    path:     /categorie/{id}
    defaults: { _controller: AnnuaireAnnuaireBundle:BienEtre:showCateg }
    


