services:
#    annuaire_annuaire.example:
#        class: Annuaire\AnnuaireBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    bienetre.search_service:
        class: Annuaire\AnnuaireBundle\Services\SearchService
        arguments: [@doctrine.orm.entity_manager]
       
    general_user.registration.form.type:
        class: Annuaire\AnnuaireBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: general_user_registration }
           
 #   prestataire.registration.form.type:
 #       class: Annuaire\AnnuaireBundle\Form\Type\RegistrationFormType
 #       arguments: [Annuaire\AnnuaireBundle\Entity\Prestataire]
#        tags:
 #           - { name: form.type, alias: prestataire_registration }
            
    #bien_etre.user_manager:
    #    class: Annuaire\AnnuaireBundle\Manager\UserManager
    #    arguments: ["%encoderFactory%", "%usernameCanonical%","%emailCanonical%","%ObjectManager%", "%class%"]
    #    calls:
    #        - { request_stack, [%request_stack%] }
            
            
 #   user_creation_listener:
 #       class: Annuaire\AnnuaireBundle\EventListeners\UserListener
 #       tags:
 #           - { name: kernel.event_subscriber }
            