services:
#    annuaire_annuaire.example:
#        class: Annuaire\AnnuaireBundle\Example
#        arguments: [@service_id, "plain_value", %parameter%]
    bienetre.search_service:
        class: Annuaire\AnnuaireBundle\Services\SearchService
        arguments: [@doctrine.orm.entity_manager]
       
    general_user.registration.form.type:
        class: Annuaire\AnnuaireBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: general_user_registration }