Annuaire\AnnuaireBundle\Entity\Localite:
    type: entity
    table: null
    repositoryClass: Annuaire\AnnuaireBundle\Entity\LocaliteRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        localite:
            type: string
            length: 255
    lifecycleCallbacks: {  }
