Annuaire\AnnuaireBundle\Entity\Prestataire:
    type: entity
    table: null
    repositoryClass: Annuaire\AnnuaireBundle\Entity\PrestataireRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nomprest:
            type: string
            length: 255
        site:
            type: string
            length: 255
        emailContact:
            type: string
            length: 255
        tel:
            type: string
            length: 255
        tva:
            type: string
            length: 255
    lifecycleCallbacks: {  }
